# =====================================================================
# The Shard programming language - shardc compiler
#
# Released under MIT License
#
# This file contains the Shard lexer, generated by PLY using a list of
# tokens and regular expressions.
# =====================================================================

# Import modules
import ply.lex as lex

# Keywords dictionnary ('keyword': 'TOKEN')
keywords = {
    'byte': 'BYTE_T',
    'word': 'WORD_T',
    'dword': 'DWORD_T',
    'qword': 'QWORD_T',
    'float': 'FLOAT_T',
    'double': 'DOUBLE_T',
    'const': 'CONST_T',
    'ubyte': 'UBYTE_T',
    'uword': 'UWORD_T',
    'udword': 'UDWORD_T',
    'uqword': 'UQWORD_T',
    'void': 'VOID_T',
    'if': 'IF',
    'else': 'ELSE',
    'forever': 'FOREVER',
    'while': 'WHILE',
    'until': 'UNTIL',
    'and': 'AND',
    'or': 'OR',
    'not': 'NOT',
    'break': 'BREAK',
    'continue': 'CONTINUE',
    'func': 'FUNC',
    'return': 'RETURN',
    'struct': 'STRUCT'
}

# Tokens tuple
tokens = (
    'COMMENT',
    'NUMBER', 'ID',
    'PLUS', 'MINUS', 'STAR', 'SLASH', 'LSHIFT', 'RSHIFT',
    'LPAR', 'RPAR', 'SEMI', 'LBRACE', 'RBRACE', 'LSQB', 'RSQB', 'COMMA', 'DOT',
    'EQUAL', 'PLUSEQ', 'MINUSEQ', 'STAREQ', 'SLASHEQ', 'ANDEQ', 'OREQ', 'XOREQ', 'NOTEQ', 'LSHIFTEQ', 'RSHIFTEQ',
    'BITAND', 'BITOR', 'XOR', 'BITNOT',
    'EQEQUAL', 'NOTEQUAL', 'LESS', 'GREAT', 'LESSEQ', 'GREATEQ'
)

# Add keywords to tokens by converting them to a tuple
tokens += tuple(keywords.values())

# Ignore space, tabs and comments (lines starting with #)
t_ignore = ' \t'
t_ignore_COMMENT = r'\#.*'

# Regular expression for numbers, handling integers and floats
t_NUMBER = r'\d+(\.\d+)?'

# Decide if the token is a keyword or an identifier
def t_ID(t):
    r'[a-zA-Z_][a-zA-Z0-9_]*'
    t.type = keywords.get(t.value, 'ID')
    return t

# Regular expressions for arithmetic and bit-shifting operators
t_PLUS = r'\+'
t_MINUS = r'-'
t_STAR = r'\*'
t_SLASH = r'/'
t_LSHIFT = r'<<'
t_RSHIFT = r'>>'

# Regular expressions for symbols
t_LPAR = r'\('
t_RPAR = r'\)'
t_SEMI = r';'
t_LBRACE = r'\{'
t_RBRACE = r'\}'
t_LSQB = r'\['
t_RSQB = r'\]'
t_COMMA = r','
t_DOT = '\.'

# Regular expressions for assignment operators
t_EQUAL = r'='
t_PLUSEQ = r'\+='
t_MINUSEQ = r'-='
t_STAREQ = r'\*='
t_SLASHEQ = r'/='
t_ANDEQ = r'&='
t_OREQ = r'\|='
t_XOREQ = r'\^='
t_NOTEQ = r'~='
t_LSHIFTEQ = r'<<='
t_RSHIFTEQ = r'>>='

# Regular expressions for bit-to-bit operators
t_BITAND = r'&'
t_BITOR = r'\|'
t_XOR = r'\^'
t_BITNOT = r'~'

# Regular expressions for comparison operators
t_EQEQUAL = r'=='
t_NOTEQUAL = r'!='
t_LESS = r'<'
t_GREAT = r'>'
t_LESSEQ = r'<='
t_GREATEQ = r'>='

# Rule to handle newlines
def t_newline(t):
    r'\n+'
    t.lineno += len(t.value)

# Handle illegal character errors
#
# Display:
# t.value       - the illegal character
# t.lineno      - the character line
# t.lexpos      - the character position
def t_error(t):
    raise SyntaxError(f"Illegal character '{t.value}' found at line {t.lineno} and position {t.value}")

# Build the lexer
lexer = lex.lex()