# =====================================================================
# The Shard programming language - shardc compiler
#
# Released under MIT License
#
# This file contains the Shard parser, generated by PLY using grammar
# rules.
# =====================================================================

# Import modules
import ply.yacc as yacc

from lexer import tokens
from tree import *

import sys
import os
from pathlib import Path
from shutil import copyfile

# shardc is converted to an executable file using PyInstaller, so this code defines 'base_path', that
# can be used to find embedded files and directories
if getattr(sys, 'frozen', False):
    base_path = Path(sys._MEIPASS)
else:
    base_path = Path(__file__).parent

# Precedence rules, for operator priorities
precedence = (
    ('right', 'EQUAL', 'PLUSEQ', 'MINUSEQ', 'STAREQ', 'SLASHEQ', 'ANDEQ', 'OREQ', 'XOREQ', 'NOTEQ', 'LSHIFTEQ', 'RSHIFTEQ'),
    ('left', 'OR'),
    ('left', 'AND'),
    ('right', 'NOT'),
    ('left', 'BITOR'),
    ('left', 'XOR'),
    ('left', 'BITAND'),
    ('nonassoc', 'LESS', 'GREAT', 'LESSEQ', 'GREATEQ', 'EQEQUAL', 'NOTEQUAL'),
    ('left', 'LSHIFT', 'RSHIFT'),
    ('left', 'PLUS', 'MINUS'),
    ('left', 'STAR', 'SLASH'),
    ('right', 'BITNOT'),
    ('right', 'POSITIVE', 'NEGATIVE')
)

# ==================== GRAMMAR RULES ======================

def p_program(p):
    """
    program : statement_list
    """
    p[0] = p[1]

def p_statement_list(p):
    """
    statement_list : statement
                   | statement_list separator statement
    """
    if len(p) == 2:
        p[0] = [p[1]] if p[1] is not None else []
    else:
        p[0] = p[1] if p[1] is not None else []
        if p[3] is not None:
            p[0] += [p[3]]

def p_statement(p):
    """
    statement : empty
              | expression
              | declaration
              | codeblock
              | condition
              | loop
              | flow_control
              | function_definition
              | struct_definition
              | inline_c
    """
    p[0] = p[1]

#
# # this is a comment
# %spp_instruction
def p_empty(p):
    """
    empty :
          | COMMENT
          | PP
    """
    pass

# 0(.0)-9(.9)+
def p_expression_value(p):
    """
    expression : NUMBER
    """
    p[0] = Value(p[1])

# "this is a string"
def p_expression_string(p):
    """
    expression : STRING
    """
    p[0] = String(p[1])

# id
def p_expression_variable_access(p):
    """
    expression : ID
    """
    p[0] = VariableAccess(p[1])

# id[index]
def p_expression_array_access(p):
    """
    expression : ID LSQB expression RSQB
    """
    p[0] = ArrayAccess(p[1], p[3])

# id.id
def p_expression_struct_field_access(p):
    """
    expression : ID DOT ID
    """
    p[0] = StructInstanceFieldAccess(p[1], p[3])

# id(param1, param2, ...)
# id()
def p_expression_function_call(p):
    """
    expression : ID LPAR expression_list RPAR
               | ID LPAR RPAR
    """
    if len(p) == 5:
        p[0] = FunctionCall(p[1], p[3])
    else:
        p[0] = FunctionCall(p[1], [])

# +x
# -x
# !x
# ~x
def p_expression_unary_op(p):
    """
    expression : PLUS expression %prec POSITIVE
               | MINUS expression %prec NEGATIVE
               | NOT expression
               | BITNOT expression
    """
    p[0] = UnaryOp(p[1], p[2])

# x + y | x - y | x * y | x / y
# x and y | x or y | x & y | x | y
# x ^ y | x == y | x != y | x < y
# x > y | x <= y | x >= y | x << y
# x >> y
def p_expression_binary_op(p):
    """
    expression : expression PLUS expression
               | expression MINUS expression
               | expression STAR expression
               | expression SLASH expression
               | expression AND expression
               | expression OR expression
               | expression BITAND expression
               | expression BITOR expression
               | expression XOR expression
               | expression EQEQUAL expression
               | expression NOTEQUAL expression
               | expression LESS expression
               | expression GREAT expression
               | expression LESSEQ expression
               | expression GREATEQ expression
               | expression LSHIFT expression
               | expression RSHIFT expression
    """
    p[0] = BinaryOp(p[1], p[2], p[3])

# id = y | id += y | id -= y | id *= y | id /= y
# id &= y | id |= y | id ^= y | id ~= y | id <<= y
# id >>= y
def p_expression_variable_assignment(p):
    """
    expression : ID EQUAL expression
               | ID PLUSEQ expression
               | ID MINUSEQ expression
               | ID STAREQ expression
               | ID SLASHEQ expression
               | ID ANDEQ expression
               | ID OREQ expression
               | ID XOREQ expression
               | ID NOTEQ expression
               | ID LSHIFTEQ expression
               | ID RSHIFTEQ expression
    """
    p[0] = VariableAssignment(p[1], p[2], p[3])

# id[index] = y | id[index] += y | id[index] -= y | id[index] *= y | id[index] /= y
# id[index] &= y | id[index] |= y | id[index] ^= y | id[index] ~= y | id[index] <<= y
# id[index] >>= y
def p_expression_array_assignment(p):
    """
    expression : ID LSQB expression RSQB EQUAL expression
               | ID LSQB expression RSQB PLUSEQ expression
               | ID LSQB expression RSQB MINUSEQ expression
               | ID LSQB expression RSQB STAREQ expression
               | ID LSQB expression RSQB SLASHEQ expression
               | ID LSQB expression RSQB ANDEQ expression
               | ID LSQB expression RSQB OREQ expression
               | ID LSQB expression RSQB XOREQ expression
               | ID LSQB expression RSQB NOTEQ expression
               | ID LSQB expression RSQB LSHIFTEQ expression
               | ID LSQB expression RSQB RSHIFTEQ expression
    """
    p[0] = ArrayAssignment(p[1], p[3], p[5], p[6])

# id.id = y | id.id += y | id.id -= y | id.id *= y | id.id /= y
# id.id &= y | id.id |= y | id.id ^= y | id.id ~= y | id.id <<= y
# id.id >>= y
def p_expression_struct_instance_field_assignment(p):
    """
    expression : ID DOT ID EQUAL expression
               | ID DOT ID PLUSEQ expression
               | ID DOT ID MINUSEQ expression
               | ID DOT ID STAREQ expression
               | ID DOT ID SLASHEQ expression
               | ID DOT ID ANDEQ expression
               | ID DOT ID OREQ expression
               | ID DOT ID XOREQ expression
               | ID DOT ID NOTEQ expression
               | ID DOT ID LSHIFTEQ expression
               | ID DOT ID RSHIFTEQ expression
    """
    p[0] = StructInstanceFieldAssignment(p[1], p[3], p[4], p[5])

# (x)
def p_expression_group(p):
    """
    expression : LPAR expression RPAR
    """
    p[0] = Group(p[2])

# type id
# type id = y
def p_declaration_variable(p):
    """
    declaration : datatype ID
                | datatype ID EQUAL expression
    """
    if len(p) == 3:
        p[0] = VariableDeclaration(p[1][0], p[1][1], p[2], None)
    else:
        p[0] = VariableDeclaration(p[1][0], p[1][1], p[2], p[4])

# type id[size]
# type id[size] = [element1, element2, ...]
def p_declaration_array(p):
    """
    declaration : datatype ID LSQB expression RSQB
                | datatype ID LSQB expression RSQB EQUAL LSQB expression_list RSQB
    """
    if len(p) == 6:
        p[0] = ArrayDeclaration(p[1][0], p[1][1], p[2], p[4], None)
    else:
        p[0] = ArrayDeclaration(p[1][0], p[1][1], p[2], p[4], p[8])

# {statement1; statement2; ...}
def p_codeblock(p):
    """
    codeblock : LBRACE statement_list RBRACE
    """
    p[0] = CodeBlock(p[2])

# if x {}
# if x {} else {}
def p_condition(p):
    """
    condition : IF expression codeblock
              | IF expression codeblock ELSE codeblock
    """
    if len(p) == 4:
        p[0] = Condition(p[2], p[3], [])
    else:
        p[0] = Condition(p[2], p[3], p[5])

# forever {}
def p_loop_unconditionnal(p):
    """
    loop : FOREVER codeblock
    """
    p[0] = LoopUnconditionnal(p[2])

# while x {}
# until x {}
def p_loop_conditionnal(p):
    """
    loop : WHILE expression codeblock
         | UNTIL expression codeblock
    """
    p[0] = LoopConditionnal(p[1], p[2], p[3])

# break
# continue
# return
# return x
def p_flow_control(p):
    """
    flow_control : BREAK
                 | CONTINUE
                 | RETURN
                 | RETURN expression
    """
    if len(p) == 2:
        p[0] = FlowControl(p[1], None)
    else:
        p[0] = FlowControl(p[1], p[2])

# func type id() {}
# func type id(param1, param2, ...) {}
def p_function_definition(p):
    """
    function_definition : FUNC datatype ID LPAR RPAR codeblock
                        | FUNC datatype ID LPAR parameter_list RPAR codeblock
    """
    if len(p) == 7:
        p[0] = FunctionDefinition(p[2], p[3], [], p[6])
    else:
        p[0] = FunctionDefinition(p[2], p[3], p[5], p[7])

# struct id {}
def p_struct_definition(p):
    """
    struct_definition : STRUCT ID LBRACE parameter_list RBRACE
    """
    p[0] = StructureDefinition(p[2], p[4])

# c { "code" }
def p_c(p):
    """
    inline_c : C LBRACE STRING RBRACE
    """
    p[0] = InlineC(p[3])

# ;
def p_separator(p):
    """
    separator : SEMI
    """
    p[0] = p[1]

# type
# typemodifier type
def p_datatype(p):
    """
    datatype : primary_type
             | type_modifier primary_type
    """
    p[0] = [None, p[1]] if len(p) == 2 else [p[1], p[2]]

# byte | word | dword | qword | float | double | ubyte | uword
# udword | uqword | void
def p_primary_type(p):
    """
    primary_type : BYTE_T
                 | WORD_T
                 | DWORD_T
                 | QWORD_T
                 | STRING_T
                 | FLOAT_T
                 | DOUBLE_T
                 | UBYTE_T
                 | UWORD_T
                 | UDWORD_T
                 | UQWORD_T
                 | VOID_T
                 | STRUCT ID
    """
    if len(p) == 2:
        p[0] = p[1]
    else:
        p[0] = p[2]

# const
def p_type_modifier(p):
    """
    type_modifier : CONST_T
    """
    p[0] = p[1]

# x
# x, ...
def p_expression_list(p):
    """
    expression_list : expression
                    | expression COMMA expression_list
    """
    p[0] = [p[1]] if len(p) == 2 else [p[1]] + p[3]

# type id
# type id, ...
def p_parameter_list(p):
    """
    parameter_list : parameter_declare
                   | parameter_declare COMMA parameter_list
    """
    p[0] = [p[1]] if len(p) == 2 else [p[1]] + p[3]

# type id
# type id[size]
def p_parameter_declare(p):
    """
    parameter_declare : datatype ID
                      | datatype ID LSQB expression RSQB
    """
    if len(p) == 3:
        p[0] = (p[1], p[2])
    else:
        p[0] = (p[1], p[2], p[4])

# Handle syntax errors
def p_error(p):
    if p:
        raise SyntaxError(f"Syntax error at \"{p.value}\" at line {p.lineno}")
    else:
        raise SyntaxError("Unexpected end of statement")

# Build the parser using the "parser_out" directory
parser = yacc.yacc(outputdir=(base_path / "parser_out").mkdir(parents=True, exist_ok=True))